services:
  db:
    image: postgis/postgis:18-3.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: rusa
      POSTGRES_USER: rusa
    volumes:
      - ./data/postgres:/var/lib/postgresql
